# Whether certain projectiles will crack blocks when they hit them
allow-arrow: true
allow-egg: true
allow-snowball: true

# Whether explosions will crack blocks around them
allow-explosion: true

# The radius of explosion cracks.
x-radius: 1
y-radius: 1
z-radius: 1

# Time it takes a block to go back to normal (seconds)
# The Minecraft client will remove all cracks after 15-20 seconds (or so)
# so setting a value higher than that probably won't have any impact.
regen-seconds: 5

# How often the server should check blocks for regeneration (in ticks, and 20 ticks = 1 second)
# If this is higher than 20 ticks, the regen will actually take a bit longer than what you specify
# in regen-seconds but the server performance will be better
regen-check-ticks: 20

# The damage per hit to a block. From 0 to 9 (max)
damage: 2

# Should we break blocks if they reach a cumulative damage of 10 or above?
allow-damage-break: false