# Whether certain projectiles will crack blocks when they hit them
arrow: true
egg: true
snowball: true

# Whether explosions will crack blocks around them
explosion: true

# The radius of explosion cracks.
x-radius: 1
y-radius: 1
z-radius: 1

# Time it takes a block to go back to normal (seconds)
# The Minecraft client will remove all cracks after 15-20 seconds (or so)
# so setting a value higher than that probably won't have any impact.
regen-seconds: 5

# How often the server should check blocks to see if they are expired
# AKA: The time they have existed is greater than the regen seconds
# Remember, 20 ticks = 1 second
regen-check-ticks: 30

# 0–9 are the displayable destroy stages. Any other number resets the block cracking.
damage: 2