# Whether certain projectiles will crack blocks when they hit them
arrow: true
egg: true
snowball: true

# Whether explosions will crack blocks around them
explosion: true

# The radius of explosion cracks.
# The higher you go, the lower the TPS
x-radius: 1
y-radius: 1
z-radius: 1

# Time it takes a block to go back to normal (seconds).
# The Minecraft client will remove all cracks after 15 seconds so setting a value higher than that won't have any impact.
# The lower you go, the lower the TPS.
regeneration: 5

# 0–9 are the displayable destroy stages. Any other number resets the block cracking.
damage: 5